const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
if(document.querySelector("#art")){
const canvas=document.querySelector('#art'),ctx=canvas.getContext('2d');let angle=0,paused=reduced,pointer={x:0,y:0},frame;
function resize(){const r=canvas.getBoundingClientRect();canvas.width=r.width*Math.min(devicePixelRatio,2);canvas.height=r.height*Math.min(devicePixelRatio,2)}resize();window.addEventListener('resize',resize);
canvas.addEventListener('pointermove',e=>{const r=canvas.getBoundingClientRect();pointer.x=(e.clientX-r.left)/r.width-.5;pointer.y=(e.clientY-r.top)/r.height-.5;if(paused)draw()});canvas.addEventListener('pointerleave',()=>{pointer={x:0,y:0};if(paused)draw()});
function draw(){const w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);const points=[];for(let i=0;i<170;i++){const t=i/170*Math.PI*2;for(let j=0;j<16;j++){const v=j/16*Math.PI*2;const r=1+.34*Math.cos(3*t);let x=(r+.22*Math.cos(v))*Math.cos(2*t),y=(r+.22*Math.cos(v))*Math.sin(2*t),z=.55*Math.sin(3*t)+.22*Math.sin(v);let a=angle*.35+pointer.x*.8,b=.5+pointer.y*.6;let xx=x*Math.cos(a)+z*Math.sin(a),zz=-x*Math.sin(a)+z*Math.cos(a),yy=y*Math.cos(b)-zz*Math.sin(b);z=y*Math.sin(b)+zz*Math.cos(b);const s=Math.min(w,h)*.29/(1+z*.13);points.push({x:w*.51+xx*s,y:h*.47+yy*s,z,j})}}points.sort((a,b)=>b.z-a.z);for(const p of points){const depth=(1.6-p.z)/3.2;ctx.fillStyle=`rgba(${150+depth*65},${176+depth*62},${72+depth*52},${.18+depth*.7})`;ctx.beginPath();ctx.arc(p.x,p.y,Math.max(1,w*.0023*(.7+depth)),0,Math.PI*2);ctx.fill()}if(!paused){angle+=.009;frame=requestAnimationFrame(draw)}}
const motion=document.querySelector('#motion');function motionLabel(){motion.textContent=paused?'Play motion ▷':'Pause motion Ⅱ';motion.setAttribute('aria-pressed',String(paused))}motionLabel();motion.addEventListener('click',()=>{paused=!paused;motionLabel();cancelAnimationFrame(frame);draw()});draw();
}
function time(){if(document.querySelector('#clock'))document.querySelector('#clock').textContent=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Kolkata',hour:'2-digit',minute:'2-digit'}).format(new Date())+' IST'}time();setInterval(time,60000);document.querySelector('#year').textContent=new Date().getFullYear();
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.section-head,.project,.concept,.about-copy').forEach(el=>{if(!reduced){el.classList.add('reveal');observer.observe(el)}});
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b))});document.querySelectorAll('.concept').forEach(c=>{c.hidden=b.dataset.filter!=='all'&&c.dataset.category!==b.dataset.filter})}));
const modal=document.querySelector('#modal'),content=document.querySelector('#modal-content');let opener;function open(html,button){opener=button;content.innerHTML=html;modal.showModal();document.body.style.overflow='hidden'}function close(){modal.close()}document.querySelector('.close').onclick=close;modal.addEventListener('close',()=>{document.body.style.overflow='';opener?.focus()});modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)close()}});
const projects={store:{title:'Digital Store',type:'E-COMMERCE / FULL-STACK PROJECT',body:'A MERN e-commerce application with product filters, a shopping cart, order workflows and user authentication. Built with React, Node.js, Express and MongoDB.',detail:'The project received second prize in the Sunstone Summer Tech Project competition. The portfolio artwork is a presentation concept rather than a screenshot of the application.',tags:['React','Express','Node.js','MongoDB','Authentication','Orders']},api:{title:'Department & Employee API',type:'BACKEND ENGINEERING / JAVA PROJECT',body:'A Spring Boot REST API for department and employee management, with create, read, update and delete operations and pagination.',detail:'This is a backend project. The dashboard shown in the portfolio is an illustrative interface with sample data, not an implemented admin frontend.',tags:['Java','Spring Boot','REST API','CRUD','Pagination']}};
document.querySelectorAll('[data-project]').forEach(b=>b.onclick=()=>{const p=projects[b.dataset.project];open(`<span class="kicker">${p.type}</span><h2>${p.title}</h2><p>${p.body}</p><div class="tags">${p.tags.map(t=>`<span>${t}</span>`).join('')}</div><p>${p.detail}</p><a class="primary" href="mailto:rasika.ghatpande24@gmail.com?subject=Project%20walkthrough">Request a project walkthrough ↗</a>`,b)});
const demos={commerce:{title:'Editorial commerce',intro:'A clean storefront direction for curated products. Try the product controls below.',surface:`<div class="demo-surface commerce"><small>FORME / INTERACTIVE CONCEPT</small><h3>Good things.<br>Considered carefully.</h3><div class="demo-products"><button data-add="Everyday tote"><strong>Everyday tote</strong>₹890 · Add to bag +</button><button data-add="Desk journal"><strong>Desk journal</strong>₹490 · Add to bag +</button><button data-add="Daily cup"><strong>Daily cup</strong>₹690 · Add to bag +</button></div><div class="demo-feedback" aria-live="polite">Your demo bag is empty.</div><button id="clear-bag">Clear bag</button></div>`,note:'Demo only: no checkout or payment is connected. A commissioned store can include product management, checkout and order tracking.'},wellness:{title:'Wellness & lifestyle',intro:'A calm, typography-led direction for coaches and studios. Select a sample session to see its details.',surface:`<div class="demo-surface wellness"><small>STILL / INTERACTIVE CONCEPT</small><h3>Make space for yourself.</h3><div class="demo-products"><button data-session="Morning flow · 45 minutes · A gentle, flowing start to the day.">Morning flow</button><button data-session="Strength & balance · 50 minutes · Controlled movement and steady holds.">Strength & balance</button><button data-session="Evening reset · 30 minutes · Slow movement and guided breathwork.">Evening reset</button></div><div class="demo-feedback" aria-live="polite">Choose a session to explore.</div></div>`,note:'Sample sessions only; selecting one does not make a booking. A commissioned studio website can include schedules, bookings and programme payments.'},business:{title:'Modern business',intro:'A bold direction for service businesses and digital products. Switch between example service packages.',surface:`<div class="demo-surface business"><small>ORBIT / INTERACTIVE CONCEPT</small><h3>A clearer path forward.</h3><div class="demo-products"><button data-plan="Launch: Brand introduction, service pages and an enquiry flow.">Launch</button><button data-plan="Grow: A content-led website with a blog, lead capture and analytics integration.">Grow</button><button data-plan="Scale: Custom workflows, an admin dashboard and integrations scoped to your business.">Scale</button></div><div class="demo-feedback" aria-live="polite">Select a package to explore its example scope.</div></div>`,note:'These are illustrative scopes, not fixed offers or prices. The final features and delivery plan are agreed for each project.'}};
document.querySelectorAll('[data-demo]').forEach(b=>b.onclick=()=>{const d=demos[b.dataset.demo];open(`<span class="kicker">WEBSITE DIRECTION / LIVE INTERACTION DEMO</span><h2>${d.title}</h2><p>${d.intro}</p>${d.surface}<p>${d.note}</p><a class="primary" href="mailto:rasika.ghatpande24@gmail.com?subject=${encodeURIComponent('Website enquiry: '+d.title)}">Discuss this direction ↗</a>`,b);let count=0,total=0;content.querySelectorAll('[data-add]').forEach((a,i)=>a.onclick=()=>{count++;total+=[890,490,690][i];content.querySelector('.demo-feedback').textContent=`${count} item${count>1?'s':''} in your demo bag · ₹${total.toLocaleString('en-IN')}`});const clear=content.querySelector('#clear-bag');if(clear)clear.onclick=()=>{count=total=0;content.querySelector('.demo-feedback').textContent='Your demo bag is empty.'};content.querySelectorAll('[data-session],[data-plan]').forEach(a=>a.onclick=()=>{content.querySelectorAll('.chosen').forEach(x=>x.classList.remove('chosen'));a.classList.add('chosen');content.querySelector('.demo-feedback').textContent=a.dataset.session||a.dataset.plan})});
